Aplicação/Aplicação/Aplicação/Controllers/CadastroController.cs
using Aplicação.DAL;
using Aplicação.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aplicação.Controllers
{
    public class CadastroController : Controller
    {
        UsuarioDAL usuarioDAL = new UsuarioDAL();

        // GET: Cadastro
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cadastro
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario, HttpPostedFileBase imagem = null)
        {
            int idade = DateTime.Now.Subtract(usuario.Data_Nascimento).Days;
            idade = idade / 365;

            if (idade >= 14)
            {
                if (imagem != null)
                {
                    usuario.ImagemMimeType = imagem.ContentType;
                    usuario.Imagem = SetImagemUser(imagem);
                    usuario.NomeArquivo = imagem.FileName;
                    usuario.TamanhoArquivo = imagem.ContentLength;
                }
                usuarioDAL.GravarUsuario(usuario);
                return RedirectToAction("../Pet/Create", new { UserID = usuario.ID, new_pet = false });
            }
            else
            {
                ViewBag.VerificaIdade = "Sua idade deve ser maior ou igual a 14 anos";
                return View(usuario);
            }
        }

        private byte[] SetImagemUser(HttpPostedFileBase imagem)
        {
            var bytesImagem = new byte[imagem.ContentLength];
            imagem.InputStream.Read(bytesImagem, 0, imagem.ContentLength);
            return bytesImagem;
        }

        public FileContentResult GetImagemUser(long id)
        {
            Usuario usuario = usuarioDAL.ObterUsuarioPorId(id);
            if (usuario != null && usuario.Imagem != null)
            {
                return File(usuario.Imagem, usuario.ImagemMimeType);
            }
            return null;
        }
    }
}

Aplicação/Aplicação/Aplicação/Controllers/HomeController.cs
using Aplicação.DAL;
using Aplicação.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aplicação.Controllers
{
    public class HomeController : Controller
    {
        PostagemDAL postDAL = new PostagemDAL();
        UsuarioDAL userDAL = new UsuarioDAL();
        
        //GET: Index
        public ActionResult Index()
        {
            return View();
        }

        //GET: Perfil
        public ActionResult Perfil(long UserID)
        {
            ViewBag.UserID = UserID;
            return View(userDAL.GetUserByID(UserID));
        }

        //GET: Editar Perfil
        public ActionResult EditarPerfil(long userID)
        {
            Usuario usuario = userDAL.GetUserByID(userID);
            ViewBag.UserID = userID;
            return View(usuario);
        }

        //POST: Editar Perfil
        [HttpPost]
        public ActionResult EditarPerfil(Usuario usuario, HttpPostedFileBase imagem, string chkRemoverImagem)
        {
            if (ModelState.IsValid)
            {
                if (chkRemoverImagem != null)
                {
                    usuario.Imagem = null;
                }
                if (imagem != null)
                {
                    usuario.ImagemMimeType = imagem.ContentType;
                    usuario.Imagem = SetImagemUser(imagem);
                    usuario.NomeArquivo = imagem.FileName;
                    usuario.TamanhoArquivo = imagem.ContentLength;
                }
                userDAL.GravarUsuario(usuario);
                return RedirectToAction("Perfil", new { UserID = usuario.ID });
            }

            return View(usuario);

            
        }

        //POST: Deletar Usuario
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarUsuario(long id)
        {
            
                Usuario user = userDAL.EliminarUsuarioPorId(id);
                TempData["Message"] = "Usuário " + user.Nome.ToUpper() + " foi removido";
                return RedirectToAction("../Cadastro/Create");
            /*try
            { 
            }
            catch
            {
                return RedirectToAction("Perfil", new { UserID = id });
            }*/
        }


        // GET: Feed
        public ActionResult Feed(int UserID)
        {
            ViewBag.UserID = UserID;
            return View(postDAL.ObterPostagensClassificadasPorData());
        }

        private byte[] SetImagemUser(HttpPostedFileBase imagem)
        {
            var bytesImagem = new byte[imagem.ContentLength];
            imagem.InputStream.Read(bytesImagem, 0, imagem.ContentLength);
            return bytesImagem;
        }
    }
}

Aplicação/Aplicação/Aplicação/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aplicação.Models;
using Aplicação.DAL;

namespace Aplicação.Controllers
{
    public class LoginController : Controller
    {
        UsuarioDAL usuarioDAL = new UsuarioDAL();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        // POST: Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Usuario usuario)
        {
            try
            {
                Usuario userWithThatEmail = usuarioDAL.GetUserByEmail(usuario.Email);
                if (usuario.Senha == userWithThatEmail.Senha)
                {
                    return RedirectToAction("../Home/Feed", new { UserID = userWithThatEmail.ID });
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

    }
}

Aplicação/Aplicação/Aplicação/Controllers/MensagemController.cs
using Aplicação.DAL;
using Aplicação.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aplicação.Controllers
{
    public class MensagemController : Controller
    {
        MensagemDAL mensagemDAL = new MensagemDAL();
        UsuarioDAL usuarioDAL = new UsuarioDAL();

        //GET
        public ActionResult Comentar(int UserID, int PostID)
        {
            ViewBag.Comments = mensagemDAL.GetCommentsByPostID(PostID);
            ViewBag.UserID = UserID;
            return View();
        }

        // POST: Comentar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Comentar(Mensagem comentario)
        {
            try
            {
                comentario.Data = DateTime.Today;
                if (ModelState.IsValid)
                {
                    mensagemDAL.GravarComentario(comentario);
                }

                ViewBag.Comments = mensagemDAL.GetCommentsByPostID(comentario.PostID);
                //return View(comentario);
                return RedirectToAction("../Mensagem/Comentar", new { UserID = comentario.UserID, PostID = comentario.PostID });
            }
            catch
            {
                ViewBag.Comments = mensagemDAL.GetCommentsByPostID(comentario.PostID);
                return View(comentario);
            }

        }

        public string GetUserName(long UserID)
        {
            Usuario usuario = usuarioDAL.ObterUsuarioPorId(UserID);
            return usuario.Nome;
        }
    }
}

Aplicação/Aplicação/Aplicação/Controllers/PostagemController.cs
using Aplicação.DAL;
using Aplicação.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aplicação.Controllers
{
    public class PostagemController : Controller
    {
        PostagemDAL postDAL = new PostagemDAL();
        UsuarioDAL userDAL = new UsuarioDAL();

        private byte[] SetImagem(HttpPostedFileBase imagem)
        {
            var bytesImagem = new byte[imagem.ContentLength];
            imagem.InputStream.Read(bytesImagem, 0, imagem.ContentLength);
            return bytesImagem;
        }

        public FileContentResult GetImagem(long id)
        {
            Postagem post = postDAL.ObterPostagemPorId(id);
            if (post != null && post.Imagem != null)
            {
                return File(post.Imagem, post.ImagemMimeType);
            }
            return null;
        }

        // GET: Publicar
        public ActionResult Publicar(int UserID)
        {
            ViewBag.UserID = UserID;
            ViewBag.Data = DateTime.Now.ToString();
            return View();
        }

        // POST: Publicar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Publicar(Postagem post, HttpPostedFileBase imagem = null)
        {
            if (ModelState.IsValid)
            {
                if (imagem != null)
                {
                    post.ImagemMimeType = imagem.ContentType;
                    post.Imagem = SetImagem(imagem);
                    post.NomeArquivo = imagem.FileName;
                    post.TamanhoArquivo = imagem.ContentLength;
                }

                postDAL.GravarPost(post);
                return RedirectToAction("../Home/Feed", new { UserID = post.UserID });
            }

            return View(post);

        }

        // POST: Deletar Postagem
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarPostagem(long postID, long userID)
        {
            Postagem post = postDAL.EliminarPostagemPorId(postID);
            TempData["Message"] = "Postagem excluída com sucesso!";
            return RedirectToAction("../Home/Perfil", new { UserID = userID });
        }

        // GET: Like
        public long? Like(long postID)
        {
            return postDAL.RegistrarLike(postID);
        }
    }
}

Aplicação/Aplicação/Aplicação/Views/Home/Feed.cshtml
@model IEnumerable<Aplicação.Models.Postagem>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Feed</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: #EB7E2F;
            @*height: 100px;*@
            margin-bottom:60px;
        }
        #botaocomentar {
            text-align:center;
            background-color: #2A5594;
            color: white;
            border-color: #2A5594;
            margin-left: 5%
        }

        @*.content-inside {
            padding: 20px;
            padding-bottom: 50px;
        }*@

        footer {
            @*height: 50px;
            margin-top: -50px;*@
            position:fixed;
            bottom:0;
            width:100vw;
            text-align:center;
            display:flex;
            justify-content:space-between;
        }
        footer div{
            margin:0 1em;
        }
        a{
            text-decoration:none;
        }
    </style>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="https://kit.fontawesome.com/d17ae299ca.js" crossorigin="anonymous"></script>
    
</head>

<body>
    <div class='nav-brand'>
        <a href='/Home'>
            <img src='https://github.com/PI-InfoWeb-CNAT/petgram/blob/login_sem_identity/images/logo_branca_petgram.png?raw=true' alt='Logo PetGram' style="width:40%; height:40%; margin-left:30%; margin-right:30%">
        </a>
    </div>

    @*foreach (var item in Model)
        {

            @Html.DisplayFor(modelItem => item.UserID)

            @Html.DisplayFor(modelItem => item.Data)

            @Html.DisplayFor(modelItem => item.Descricao)

            @Html.DisplayFor(modelItem => item.Visibilidade)

            @Html.DisplayFor(modelItem => item.Filtro)

        }*@

    @*Html.ActionLink("Publicar postagem", "Publicar", "Postagem", new { UserID = ViewBag.UserID }, null)
        <div style="display: inline-block; margin-left: 1%;"><a href="~/Views/Postagem/Publicar.cshtml" class="fas fa-camera fa-lg" style="text-decoration:none; color:white"></a></div>*@

    @foreach (var item in Model)
    {
        <div class="card col align-items-left" style="margin-left: 15%; margin-right: 15%; width: 70%; margin-top:1%; background-color: #EB7E2F; border-color: #EB7E2F">

            <a href="@Url.Action("Perfil", "Home", new { UserId = ViewBag.UserID })" style="text-decoration:none">
                <div class="social-avatar" style="">
                    <img class="img-thumbnail img-responsive my-image" style="height: 40px; width: 40px;" src="@Url.Action("GetImagemUser", "Cadastro", new { id = item.UserID })" />

                    <h5 style="color: white; display: inline-block">@Html.DisplayFor(modelItem => item.User.Nome)</h5>
                    <!-- Nome do usuário da pessoa que postou ao lado da imagem -->

                </div>
            </a>

            <img class="img-thumbnail img-responsive" style="margin-top:5px" src="@Url.Action("GetImagem", "Postagem", new { id = item.ID })" />

            <div class="like_and_comment" style="margin-top:1%">

                <a onclick="DarLike(this.id)" id="@item.ID.ToString()" style="cursor: pointer;"><i class="fa fa-paw fa-lg" style="color:white"></i> <span style="color:white">@item.Likes</span></a>

                <script>
                    function DarLike(id) {
                        idString = "#" + id + " span";
                        $.get("../Postagem/Like?postID=" + id, function (result) {
                            $(idString).html(result);
                        });
                    }

                </script>

                <a href="@Url.Action("Comentar", "Mensagem", new { UserID = ViewBag.UserID, PostID = item.ID })">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"></path>
                    </svg>
                </a>
                <span style="color:white">@item.Comentarios.Count</span>
            </div>
            <h6 style="color: white">@Html.DisplayFor(modelItem => item.Descricao)</h6>
        </div>

        <hr style="color:#FD9448; height:4px">
    }

    <footer style="background-color: #2A5594; height: 50px">
        <div style="display: inline-block; margin-top: 15px"><a href="@Url.Action("Feed", "Home", new { UserId = ViewBag.UserID })" class="fas fa-home fa-lg" style="text-decoration:none; color:white"></a></div>
        <div style="display: inline-block; margin-top: 15px"><a href="@Url.Action("Publicar", "Postagem", new { UserId = ViewBag.UserID })" class="fas fa-camera fa-lg" style="text-decoration:none; color:white"></a></div>
        <div style="display: inline-block; margin-top: 15px"><a href="@Url.Action("Perfil", "Home", new { UserId = ViewBag.UserID })" class="fas fa-user fa-lg" style="text-decoration:none; color:white"></a></div>
    </footer>
</body>
</html>

Aplicação/Aplicação/Aplicação/Views/Home/Perfil.cshtml
@model Aplicação.Models.Usuario

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Perfil</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>

        body {
            background-color: #EB7E2F;
            @*height: 100px;*@
            margin-bottom:60px;
        }
        footer {
            @*height: 50px;
            margin-top: -50px;*@
            position:fixed;
            bottom:0;
            width:100vw;
            text-align:center;
            display:flex;
            justify-content:space-between;
        }
        footer div{
            margin:0 1em;
        }
        @**.my-image {
            height: 40px;
            width: 40px;
        }

        .social-avatar {
            padding: 15px 15px 0 15px;
        }

        .social-avatar img {
            height: 40px;
            width: 40px;
            margin-right: 10px;
        }*@

        #botaoeditar {
            text-decoration: none;
            text-align: center;
            background-color: #2A5594;
            color: white;
            border-color: #2A5594;
            width: 30%
        }

        #botaoexcluir {
            text-decoration: none;
            text-align: center;
            color: white;
            background-color: red;
            border-color: red;
            width:30%
        }

        a{
            text-decoration:none
        }

        #fotoperfil{
            margin-top: 2%;
            width: 30%;
            height: 30%;
            margin-left: 35%;
            margin-right: 35%
        }
        .fa-solid:before {
            content: "\f015";
        }
    </style>
    <script src="https://kit.fontawesome.com/d17ae299ca.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>
<body>

    <div class='nav-brand'>
        <a href='/Home'>
            <img src='https://github.com/PI-InfoWeb-CNAT/petgram/blob/login_sem_identity/images/logo_branca_petgram.png?raw=true' alt='Logo PetGram' style="width:40%; height:40%; margin-left:30%; margin-right:30%">
        </a>
    </div>
    <div>
        @*<div style="margin-left: 1%; color: white">
                   @Html.DisplayFor(model => model.User)
            </div>*@
        <img class="img-thumbnail img-responsive my-image" id="fotoperfil" src="@Url.Action("GetImagemUser", "Cadastro", new { id = Model.ID })" />
        <dl class="dl-horizontal" style="color: white; text-align:center">

            <dt>
                @*Html.DisplayNameFor(model => model.User)*@
                Nome de usuário:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.User)
            </dd>


            <dt>
                @*Html.DisplayNameFor(model => model.Nome)*@
                Nome:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>


            @*<dt>
                    @Html.DisplayNameFor(model => model.Data_Nascimento)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Data_Nascimento)
                </dd>*@

            <dt>
                @*Html.DisplayNameFor(model => model.Descricao)*@
                Descrição:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Descricao)
            </dd>

            @*<dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>*@

            @*<dt>
                    @Html.DisplayNameFor(model => model.Senha)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Senha)
                </dd>*@
        </dl>
    </div>
    <hr style="color:#FD9448; height:4px">

    <h4 style="margin-left: 1%; color: white; text-align:center">Meus pets:</h4>
    @foreach (var item in Model.Pets)
    {

        <dl style="margin-left:1%; color:white; text-align:center">
            <dt>
                @*Html.DisplayNameFor(modelItem => item.Name)*@
                Nome:
            </dt>
            <dd>
                @Html.DisplayFor(modelItem => item.Name)
            </dd>


            <dt>
                @*Html.DisplayNameFor(modelItem => item.Category)*@
                Categoria:
            </dt>
            <dd>
                @Html.DisplayFor(modelItem => item.Category)
            </dd>


            <dt>
                @*Html.DisplayNameFor(modelItem => item.Description)*@
                Descrição:
            </dt>
            <dd>
                @Html.DisplayFor(modelItem => item.Description)
            </dd>
        </dl>
    }
    <hr style="color:#FD9448; height:4px">

    @*Html.ActionLink("Editar perfil", "EditarPerfil", new { userID = ViewBag.UserID })*@

    <br />

    @foreach (var item in Model.Postagens)
    {
        <div class="card col align-items-left" style="margin-left: 15%; margin-right: 15%; width: 70%; background-color: #EB7E2F; border-color: #EB7E2F">

            @*<a href="@Url.Action("Perfil", "Home", new { UserId = ViewBag.UserID })" style="text-decoration:none">
                    <div class="social-avatar" style="">
                        <img class="img-thumbnail img-responsive my-image" style="height: 40px; width: 40px;" src="@Url.Action("GetImagemUser", "Cadastro", new { id = ViewBag.UserID })" />

                        <h5 style="color: white; display: inline-block">@Html.DisplayFor(modelItem => item.User.Nome)</h5>
                        <!-- Nome do usuário da pessoa que postou ao lado da imagem -->

                    </div>
                </a>*@

            <img class="img-thumbnail img-responsive" style="margin-top:5px" src="@Url.Action("GetImagem", "Postagem", new { id = item.ID })" />

            <div class="like_and_comment" style="margin-top:1%">

                <a onclick="DarLike(this.id)" id="@item.ID.ToString()" style="cursor: pointer;"><i class="fa fa-paw fa-lg" style="color:white"></i> <span style="color:white">@item.Likes</span></a>

                <script>
                    function DarLike(id) {
                        idString = "#" + id + " span";
                        $.get("../Postagem/Like?postID=" + id, function (result) {
                            $(idString).html(result);
                        });
                    }

                </script>

                <a href="@Url.Action("Comentar", "Mensagem", new { UserID = ViewBag.UserID, PostID = item.ID })">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"></path>
                    </svg>
                </a>
                <span style="color:white">@item.Comentarios.Count</span>
            </div>
            <h6 style="color: white">@Html.DisplayFor(modelItem => item.Descricao)</h6>
        </div>
        <hr style="color:#FD9448; height:4px">
    }


    <div class="form-group">
        <div style="text-align: center">
            @Html.ActionLink("Editar perfil", "EditarPerfil", "Home", new { UserID = ViewBag.UserID }, new { @id = "botaoeditar", @class = "btn btn-default" })
        </div>
        <div style="text-align: center; margin-top:1% ">
            @using (Html.BeginForm("DeletarUsuario", "Home", new { id = ViewBag.UserID }, FormMethod.Post, new { @id = "delete-user-form", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Excluir conta" id="botaoexcluir" class="btn btn-danger" />
            }
        </div>
    </div>

    <footer style="background-color: #2A5594; height: 50px">
        <div style="display: inline-block; margin-top: 15px"><a href="@Url.Action("Feed", "Home", new { UserId = ViewBag.UserID })" class="fas fa-home fa-lg" style="text-decoration:none; color:white"></a></div>
        <div style="display: inline-block; margin-top: 15px"><a href="@Url.Action("Publicar", "Postagem", new { UserId = ViewBag.UserID })" class="fas fa-camera fa-lg" style="text-decoration:none; color:white"></a></div>
        <div style="display: inline-block; margin-top: 15px"><a href="@Url.Action("Index", "Login")" class="fas fa-door-open fa-lg" style="text-decoration:none; color:white"></a></div>
    </footer>
</body>
</html>